#!/bin/bash

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

# Install pipenv
pip install -q pipenv --user

# Install application dependencies
script/bootstrap
