#!/bin/bash

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

createdb authz || echo 'Database exists; skipping'

# Install pipenv
if [ -n "$CI" ]; then
  pip install pipenv
else
  pip install -q pipenv --user
fi

# Install application dependencies
script/bootstrap
