#!/bin/bash

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

if [ "$1" = "watch" ]; then
  ag -l -G [py]$ | entr pipenv run python -m pytest
else
  pipenv run pylint authz tests app.py
  pipenv run python -m pytest -s
fi
